services:
  # Reuse your existing database configurations with test-specific settings
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: spree_test
    volumes:
      - 'postgres_test:/var/lib/postgresql/data'
    ports:
      - "5432:5432"
    networks:
      - spree_test_network

  postgres_queue:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: spree_queue_test
    volumes:
      - 'postgres_queue_test:/var/lib/postgresql/data'
    ports:
      - "5433:5432"
    networks:
      - spree_test_network

  # Add Redis for caching/jobs if your application needs it
  redis:
    image: redis:6
    ports:
      - "6379:6379"
    networks:
      - spree_test_network

  # Your web application using the existing Dockerfile
  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - RAILS_ENV=test
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_PORT=5432
      - QUEUE_DB_HOST=postgres_queue
      - QUEUE_DB_USER=postgres
      - QUEUE_DB_PASSWORD=password
      - QUEUE_DB_PORT=5432
      - REDIS_URL=redis://redis:6379/1
    ports:
      - "3000:3000"
    networks:
      - spree_test_network
    depends_on:
      - postgres
      - postgres_queue
      - redis
    command: >
      bash -c "
        bin/rails db:prepare &&
        bin/rails db:seed &&
        bin/rails log:clear tmp:clear &&
        bin/rails server -b 0.0.0.0
        "

  # Playwright testing container
  playwright:
    image: mcr.microsoft.com/playwright:v1.52.0-noble
    working_dir: /app/playwright
    volumes:
      - .:/app
      - playwright-cache:/root/.cache/ms-playwright
      - ./playwright/playwright-report:/app/playwright/playwright-report
      - ./playwright/test-results:/app/playwright/test-results
    environment:
      - BASE_URL=http://web:3000
      - CI=true
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
    networks:
      - spree_test_network
    depends_on:
      - web
    command: >
      /bin/sh -c "
        npm ci &&
        npx playwright test
        "

networks:
  spree_test_network:

volumes:
  postgres_test:
  postgres_queue_test:
  playwright-cache: