services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    ports:
      - "5432:5432"
  postgres_queue:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - 'postgres_queue:/var/lib/postgresql/data'
    ports:
      - "5433:5432"
  playwright:
    image: mcr.microsoft.com/playwright:v1.52.0-noble
    depends_on:
      - web  
    working_dir: /tests
    volumes:
      - ./playwright-tests:/tests
    command: ["npx", "playwright", "test"]

volumes:
  postgres:
  postgres_queue:
  playwright: