name: Playwright Test

on:
  # push:
  #   branches: 
  #     - main
  pull_request:
    branches: 
      - main

jobs:
  environment-setup:
    name: Set Up Environment 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies 
        if: ${{ !env.ACT }}
        run: sudo apt-get install libvips-dev libpq-dev
      
      # Set up Ruby
      - name: Install Ruby 
        uses: ruby/setup-ruby@v1
        with: 
            ruby-version: '3.3.0'
            bundler-cache: true

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        working-directory: ./playwright
        run: npm ci

      - name: Set up services with Docker Compose
        uses: docker/setup-compose-action@v1
        with: 
          version: latest

      - name: Start Docker Compose services
        run: docker compose up -d

      - name: Check running containers
        run: docker ps -a

      - name: Setup application setup
        run: ./bin/setup

      - name: Run application services
        run: |
          ./bin/dev &
          sleep 30 
          echo "Testing via localhost1"
          curl -v http://0.0.0.0:3000

  # playwright:
  #   name: Run Playwright Tests
  #   needs: environment-setup
  #   runs-on: ubuntu-latest

  #   steps:
  #   - uses: actions/checkout@v4

        
      - name: Install Playwright Browsers
        working-directory: ./playwright
        run: npx playwright install --with-deps  

      # - name: Checking on the port 
      #   run: |
      #     echo "Testing via localhost2"
      #     curl -v http://localhost:3000

      - name: Run your tests
        run: npx playwright test
        working-directory: ./playwright
        env:
          BASE_URL: http://0.0.0.0:3000

      - name: Stop Docker Compose services
        if: always()
        run: |
          pwd
          docker compose down
        working-directory: .
      
      - name: Upload test artifacts
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: playwright/test-results
          retention-days: 1
          if-no-files-found: ignore
