name: Playwright Test

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main

jobs:
  environment-setup:
    name: Set Up Environment 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install dependencies 
        run: sudo apt-get install libvips-dev libpq-dev
      
      # Set up Ruby
      - name: Install Ruby 
        uses: ruby/setup-ruby@v1
        with: 
            ruby-version: '3.3.0'
            bundler-cache: true

      - name: Verify Ruby setup
        run: |
          ruby -v
          gem -v
          bundle -v

      - name: Set Up Services With Docker Compose
        uses: docker/setup-compose-action@v1
        with: 
          version: latest

      - name: Start Docker Compose Services
        run: docker compose up -d

      - name: Check running containers
        run: docker ps -a

      - name: Setup application setup
        run: ./bin/setup

      - name: Run application services
        run: ./bin/dev   
    
      # - name: Setup test database
      #   if: ${{ !env.ACT }} 
      #   run: bundle exec rails db:setup RAILS_ENV=test
        
      - name: Load Spree sample data
        run: bin/rake spree_sample:load


  test:
    name: Run Playwright Tests
    needs: environment-setup
    runs-on: ubuntu-latest
    defaults:
        run:
            working-directory: ./playwright

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    
    - name: Install dependencies
      run: docker compose exec -T app npm ci

    - name: Install Playwright dependencies
      run: docker compose exec -T app npx playwright install --with-deps
    
    - name: Run Playwright Tests
      run: docker compose exec -T app npx playwright test --config=playwright/playwright.config.js
      env:
        BASE_URL: http://localhost:3000
    
    - name: Stop Docker Compose services
      if: always()
      run: docker compose down
    
    - name: Upload test artifacts
      if: ${{ !cancelled() }}
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: |
          playwright/test-results
          playwright/playwright-report
        retention-days: 1
        if-no-files-found: ignore



